### ISSUE TITLE
Use evaluation and explanation as a standalone package?

### ISSUE THREAD

**Issue by ydennisy** [sergioburdisso/pyss3#14] opened 2020-09-18 12:00 UTC
Hey, cool project!

Just wondering if you think it is feasible to use the explanations with other models?

**Comment by sergioburdisso** [comment] 2020-09-21 15:46
Hey @ydennisy! Thanks :D

I think it could be possible to use explanations with other models, as long as the Live Test tool receives a JSON holding the value each word/element has, it will work regarding what model produced it. In principle, updating the server module's code ([server.py](https://github.com/sergioburdisso/pyss3/blob/master/pyss3/server.py)) so that a JSON for the classification result could be generated for other models will do the trick. However, since most of the supervised machine learning models work as black boxes, representing input documents as feature vectors, we will need to use some other method on top (such as [LIME](https://www.oreilly.com/content/introduction-to-local-interpretable-model-agnostic-explanations-lime/)) to try to infer/estimate how valuable each raw input element was according to the model. This was straightforward for the SS3 model since, by design, the model explicitly learns a confidence value for each input element and each class, and then the classification is performed directly based on those values. This confidence value tells how relevant each input element is as if we were asking "How much value has this element for this class?". e.g. after training the model, SS3 would learn something like:

```
value("apple", technology) = 0.7
value("apple", business) = 0.5
value("apple", food) = 0.9
```
and
```
value("the", technology) = value("the", business) = value("the", food) = 0
```

That is, "apple" has a value of 0.7 for technology, 0.5 for business, and .9 for food, whereas "the" has no value for any category. Note that even Multinomial Naive Bayes (a "white box" model) wouldn't work "out of the box" since it values each element by its probability (log P(w|c)) and hence (stop)words like "the", "a", "with", etc. would have the highest value (i.e. highest probability).

Regarding Evaluation, I think it is also feasible, at least for models with three hyperparameters (or less), with more than three hyperparameters we will need to think about how to adapt the Evaluation 3D Plot UI to let users select only the hyperparameters they are interested in.

![](https://media.giphy.com/media/a5viI92PAF89q/giphy.gif)

**Comment by sergioburdisso** [comment] 2020-10-01 03:17
(I'm closing this issue, but feel free to reopen it whenever you want, I'll also reopen in case sometime in the future I'm able to actually implement this. Anyways, thanks for raising the question 💪🤓👍Take care!)

**Closed by sergioburdisso** 2020-10-01 03:17 UTC
Labels: question
